#!/usr/bin/env python3
"""
Bronze Tier File System Watcher
================================

INSTALLATION REQUIRED:
    pip install watchdog

USAGE:
    python watchers/filesystem_watcher.py

DESCRIPTION:
    Monitors the /Inbox folder for new files.
    When a file is created:
    1. Copies it to /Needs_Action with FILE_ prefix
    2. Creates a .md metadata file with YAML frontmatter
    3. Logs all operations to console

MONITORING:
    Check Interval: 5 seconds
    Watch Folder: /Inbox
    Output Folder: /Needs_Action
    Metadata: YAML frontmatter with type, original_name, size, status

ERROR HANDLING:
    - Skips bad files gracefully
    - Continues monitoring after errors
    - Reports errors to console
"""

import os
import sys
import time
import shutil
from pathlib import Path
from datetime import datetime

try:
    from watchdog.observers import Observer
    from watchdog.events import FileSystemEventHandler
except ImportError:
    print("❌ ERROR: watchdog library not installed")
    print("📦 Install with: pip install watchdog")
    sys.exit(1)


class BronzeTierFileHandler(FileSystemEventHandler):
    """Handles file system events for Bronze Tier Inbox monitoring"""

    def __init__(self, project_root):
        self.project_root = Path(project_root)
        self.inbox = self.project_root / "Inbox"
        self.needs_action = self.project_root / "Needs_Action"
        self.processed_files = set()  # Track processed files to avoid duplicates

        # Ensure output directory exists
        self.needs_action.mkdir(parents=True, exist_ok=True)

    def on_created(self, event):
        """Handle file creation events"""
        # Ignore directories
        if event.is_directory:
            return

        filepath = Path(event.src_path)

        # Ignore metadata files (.md) created by this script
        # Only ignore files that have FILE_ prefix and .md extension
        if filepath.name.startswith('FILE_') and filepath.name.endswith('.md'):
            return

        # Skip if already processed
        if str(filepath) in self.processed_files:
            return

        # Add small delay to ensure file is fully written
        time.sleep(0.5)

        # Process the file
        self._process_file(filepath)

    def _process_file(self, filepath):
        """Process a new file from Inbox"""
        try:
            # Check if file still exists (might have been deleted)
            if not filepath.exists():
                print(f"⚠️  File disappeared before processing: {filepath.name}")
                return

            # Mark as processed
            self.processed_files.add(str(filepath))

            # Get file info
            filename = filepath.name
            file_size = filepath.stat().st_size
            timestamp = datetime.now().isoformat()

            print(f"\n{'='*70}")
            print(f"📥 NEW FILE DETECTED IN /Inbox")
            print(f"{'='*70}")
            print(f"⏰ Timestamp: {timestamp}")
            print(f"📄 Original Name: {filename}")
            print(f"📊 Size: {file_size} bytes")

            # Step 1: Copy file to Needs_Action with FILE_ prefix
            new_filename = f"FILE_{filename}"
            destination = self.needs_action / new_filename

            print(f"\n📋 STEP 1: COPYING FILE")
            print(f"  From: {filepath}")
            print(f"  To:   {destination}")

            try:
                shutil.copy2(filepath, destination)
                print(f"  ✓ File copied successfully")
            except Exception as e:
                print(f"  ❌ Copy failed: {str(e)}")
                return

            # Step 2: Create metadata file with YAML frontmatter
            metadata_filename = f"FILE_{filename}.md"
            metadata_path = self.needs_action / metadata_filename

            print(f"\n📋 STEP 2: CREATING METADATA FILE")
            print(f"  Path: {metadata_path}")

            yaml_frontmatter = f"""---
type: file_drop
original_name: {filename}
size: {file_size}
status: pending
created_at: {timestamp}
file_prefix: FILE_{filename}
---

# File Drop Metadata

**Original Name:** `{filename}`
**Size:** {file_size} bytes
**Status:** pending
**Created:** {timestamp}
**Destination:** `/Needs_Action/{new_filename}`

## Actions Required

- [ ] Review original file
- [ ] Determine action type
- [ ] Update status to 'processed'
- [ ] Move to /Done when complete

## Notes

This metadata file was automatically generated by the Bronze Tier File System Watcher.
The original file has been copied to `/Needs_Action/{new_filename}`.
"""

            try:
                with open(metadata_path, 'w', encoding='utf-8') as f:
                    f.write(yaml_frontmatter)
                print(f"  ✓ Metadata file created successfully")
            except Exception as e:
                print(f"  ❌ Metadata creation failed: {str(e)}")
                return

            # Step 3: Summary
            print(f"\n{'='*70}")
            print(f"✅ FILE PROCESSING COMPLETE")
            print(f"{'='*70}")
            print(f"📁 Original file: {filepath}")
            print(f"📁 Copied to: {destination}")
            print(f"📋 Metadata: {metadata_path}")
            print(f"{'='*70}\n")

        except Exception as e:
            print(f"❌ ERROR processing file {filepath.name}: {str(e)}")
            print(f"⏭️  Continuing to monitor...\n")

    def on_modified(self, event):
        """Handle file modification events (ignore)"""
        pass

    def on_deleted(self, event):
        """Handle file deletion events (ignore)"""
        pass

    def on_moved(self, event):
        """Handle file move events"""
        if not event.is_directory:
            filepath = Path(event.dest_path)
            if filepath.parent.name == "Inbox":
                self._process_file(filepath)


class BronzeTierWatcher:
    """Main watcher controller with fallback polling"""

    def __init__(self, project_root):
        self.project_root = Path(project_root)
        self.inbox = self.project_root / "Inbox"
        self.needs_action = self.project_root / "Needs_Action"
        self.observer = Observer()
        self.event_handler = BronzeTierFileHandler(project_root)
        self.known_files = set()  # Track files we've already seen
        self.last_check = time.time()

    def _polling_check(self):
        """Fallback polling method to detect new files"""
        try:
            if not self.inbox.exists():
                return

            # Get all files in Inbox
            current_files = {f.name for f in self.inbox.glob('*') if f.is_file()}

            # Find new files
            new_files = current_files - self.known_files

            for filename in new_files:
                filepath = self.inbox / filename
                # Give file time to be fully written
                time.sleep(0.5)
                if filepath.exists():
                    self.event_handler._process_file(filepath)

            # Update known files
            self.known_files = current_files
        except Exception as e:
            print(f"⚠️  Polling check error: {str(e)}")

    def start(self):
        """Start monitoring the Inbox folder"""
        # Ensure Inbox exists
        self.inbox.mkdir(parents=True, exist_ok=True)
        self.needs_action.mkdir(parents=True, exist_ok=True)

        print("\n" + "="*70)
        print("🚀 BRONZE TIER FILE SYSTEM WATCHER - STARTING")
        print("="*70)
        print(f"📍 Project Root: {self.project_root}")
        print(f"📂 Monitoring: {self.inbox}")
        print(f"📤 Output: {self.needs_action}")
        print(f"⏱️  Check Interval: 5 seconds")
        print(f"🔍 Mode: Hybrid (Watchdog + Polling)")
        print("="*70)
        print(f"✓ Watcher initialized and ready")
        print(f"✓ Watching for new files in /Inbox...")
        print(f"✓ Press Ctrl+C to stop\n")

        try:
            # Initialize known files
            if self.inbox.exists():
                self.known_files = {f.name for f in self.inbox.glob('*') if f.is_file()}

            # Schedule observer (might work on some systems)
            self.observer.schedule(
                self.event_handler,
                str(self.inbox),
                recursive=False
            )

            # Start observer
            self.observer.start()
            print(f"✓ Watchdog observer started (event-based detection)\n")

            # Keep running with polling fallback
            check_count = 0
            while True:
                time.sleep(5)  # Check interval: 5 seconds
                check_count += 1

                # Run polling check every cycle
                # This ensures detection even if watchdog fails
                self._polling_check()

        except KeyboardInterrupt:
            print("\n\n" + "="*70)
            print("🛑 WATCHER STOPPED BY USER")
            print("="*70)
            self.stop()

        except Exception as e:
            print(f"\n❌ ERROR: {str(e)}")
            print("="*70)
            self.stop()

    def stop(self):
        """Stop monitoring"""
        try:
            self.observer.stop()
            self.observer.join()
        except:
            pass
        print(f"✓ Watcher stopped")
        print(f"✓ Farewell!\n")


def verify_project_structure(project_root):
    """Verify that required folders exist"""
    project_root = Path(project_root)
    required_dirs = ["Inbox", "Needs_Action", "Plans", "Done", "Logs"]

    print("\n📋 VERIFYING PROJECT STRUCTURE:")
    missing = []

    for dir_name in required_dirs:
        dir_path = project_root / dir_name
        if dir_path.exists():
            print(f"  ✓ {dir_name}/")
        else:
            print(f"  ❌ {dir_name}/ (will be created)")
            missing.append(dir_path)

    # Create missing directories
    for dir_path in missing:
        try:
            dir_path.mkdir(parents=True, exist_ok=True)
            print(f"  ✓ Created: {dir_path.name}/")
        except Exception as e:
            print(f"  ❌ Failed to create {dir_path.name}/: {str(e)}")

    print()


def main():
    """Main entry point"""
    # Determine project root (parent of watchers directory)
    script_path = Path(__file__)
    project_root = script_path.parent.parent

    # Verify structure
    verify_project_structure(project_root)

    # Create and start watcher
    watcher = BronzeTierWatcher(project_root)
    watcher.start()


if __name__ == "__main__":
    main()
